# permissions for end users to edit mdemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mdemo-editor-role
rules:
- apiGroups:
  - mapp.mdemo.com
  resources:
  - mdemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mapp.mdemo.com
  resources:
  - mdemoes/status
  verbs:
  - get
