# permissions for end users to view mdemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mdemo-viewer-role
rules:
- apiGroups:
  - mapp.mdemo.com
  resources:
  - mdemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mapp.mdemo.com
  resources:
  - mdemoes/status
  verbs:
  - get
