
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mapp.mdemo.com
  resources:
  - mdemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mapp.mdemo.com
  resources:
  - mdemoes/finalizers
  verbs:
  - update
- apiGroups:
  - mapp.mdemo.com
  resources:
  - mdemoes/status
  verbs:
  - get
  - patch
  - update
